defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk

version: 2
jobs:
  build:
    <<: *defaults

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Build Docker Image"
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker images

      - run:
          name: "Save test results"
          command: |
            mkdir -p ~/test-results/junit
            id=$(docker create $(docker images --filter "label=buildstage" -q))
            docker cp $id:/usr/local/build/target/surefire-reports/  ~/test-results
            docker rm -v $id

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results

      - run:
          name: "Create workspace"
          command: |
            mkdir -p workspace/image
            docker save -o workspace/image/$CIRCLE_PROJECT_REPONAME-image.tar $CIRCLE_PROJECT_REPONAME:latest

      - persist_to_workspace:
          root: workspace
          paths:
            - image

  push:
    <<: *defaults
    
    steps:

      - attach_workspace:
          at: workspace

      - setup_remote_docker

      - run:
          name: "Install AWS"
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region $AWS_REGION || echo false)

      - run:
          name: "Reload and push docker image"
          command: |
            docker load < workspace/image/$CIRCLE_PROJECT_REPONAME-image.tar
            docker tag $CIRCLE_PROJECT_REPONAME:latest $AWS_ECR_HOST/$CIRCLE_PROJECT_REPONAME:latest
            docker tag $CIRCLE_PROJECT_REPONAME:latest $AWS_ECR_HOST/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
            docker push $AWS_ECR_HOST/$CIRCLE_PROJECT_REPONAME:latest
            docker push $AWS_ECR_HOST/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG

workflows:
  version: 2
  build-push:
    jobs:
      - build:
          context: gis
          filters:
            tags:
              only: /.*/
      - push:
          context: gis
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
